name: datacollect
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4=4.11.1
  - google-api-python-client=2.47.0
  - ipykernel=6.13.0
  - pandas=1.3.4
  - python=3.7.12
  - selenium=4.1.0
  - wordcloud=1.8.1
